name: SimpleLogger
main: space\yurisi\SimpleLogger
version: 2.0
api: 4.0.0
author: yurisi
website: homepage.yurisi.space

permissions:
    space.yurisi.log:
        default: op
        description: 指定した場所のログを確認